#!/bin/sh

WALLET_NAME="wallet.json"
NODE_WS_PORT="9880"
CLI_WALLET_PORT="6000"
NODE_WS_ADDRESS="ws://localhost:$NODE_WS_PORT"
CLI_WALLET_ADDRESS="0.0.0.0:6000"

./cli_wallet --wallet "$WALLET_NAME" -s "$NODE_WS_ADDRESS" -r "$CLI_WALLET_ADDRESS" -d
